In [10]:
list=[1,2,3]
list

[1, 2, 3]

In [7]:
pip install numpy


     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.2 kB ? eta -:--:--
     -------------------------------------- 61.2/61.2 kB 809.0 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.4 MB/s eta 0:00:12
   ---------------------------------------- 0.1/15.8 MB 871.5 kB/s eta 0:00:19
   ---------------------------------------- 0.1/15.8 MB 950.9 kB/s eta 0:00:17
    --------------------------------------- 0.3/15.8 MB 1.5 MB/s eta 0:00:11
   - -------------------------------------- 0.5/15.8 MB 2.3 MB/s eta 0:00:07
   - -------------------------------------- 0.8/15.8 MB 2.8 MB/s eta 0:00:06
   --- ------------------------------------ 1.2/15.8 MB 3.7 MB/s eta 0:00:04
   --- ------------------------------------ 1.4/15.8 MB 4.0 MB/s eta 0:00:04
   ---- ----------------------------------- 2.0/15.8 MB 4.8 MB/s eta 0:00:03
   -----

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'



In [8]:
import numpy as np


In [12]:
arr = np.array(list)
arr


array([1, 2, 3])

In [13]:
arr.dtype

dtype('int32')

In [14]:
arr2 = np.random.randint(1,50,size=(10))
arr2

array([47, 37, 12,  6, 47, 22, 13, 34, 21,  9])

In [15]:
arr2.size

10

In [16]:
arr2.dtype

dtype('int32')

In [17]:
np.ndim(arr2)

1

In [18]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr4 = np.random.randint(10,100,size = (2,5))
arr4

array([[57, 16, 83, 35, 42],
       [68, 96, 16, 88, 23]])

In [20]:
arr4.shape

(2, 5)