In [1]:
arr1 = np.random.randint(1, 50, size=10)


NameError: name 'np' is not defined

In [2]:
pip install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.0 kB ? eta -:--:--
     -------------------------------------- 61.0/61.0 kB 806.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.3 MB/s eta 0:00:13
   ---------------------------------------- 0.1/15.8 MB 907.3 kB/s eta 0:00:18
   ---------------------------------------- 0.1/15.8 MB 1.1 MB/s eta 0:00:15
    --------------------------------------- 0.2/15.8 MB 1.2 MB/s eta 0:00:13
   - -------------------------------------- 0.4/15.8 MB 1.9 MB/s eta 0:00:09
   - -------------------------------------- 0.5/15.8 MB 1.8 MB/s eta 0:00:09
   - -------------------------------------- 0.6/15.8 MB 1.9 MB/s eta 0:00:09
   - -------------------------------------- 0.7/15.8 MB 1.9 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/15.8 MB 2.0 MB/s eta 0:00:08
   -- ---

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
arr1 = np.random.randint(1, 50, size=10)

arr

NameError: name 'arr' is not defined

In [ ]:
arr1


In [ ]:
arr1 = np.random.randint(1, 50, size=10)

arr1


In [5]:
arr1 = np.random.randint(1, 50, size=10)

arr1


array([19, 17, 23, 37, 44, 20, 22, 29,  2, 24])

In [6]:
np.mean(arr1)

23.7

In [7]:
a1 = np.random.randint(1, 50, size=(3,3)

SyntaxError: incomplete input (2348083633.py, line 1)

In [8]:
a1 = np.random.randint(1, 50, size=(3,3))

In [9]:
a1

array([[ 7, 43, 46],
       [19, 24, 32],
       [21, 43, 46]])

In [11]:
a2 = np.random.randint(1, 50, size=(3,3))
a2
                       

array([[28, 13, 39],
       [48, 25, 26],
       [32,  4, 18]])

In [12]:
a=np.add(a1,a2)
a

array([[35, 56, 85],
       [67, 49, 58],
       [53, 47, 64]])

In [13]:
np.mean(a)

57.111111111111114

In [14]:
arr2 = np.random.randint(1, 100, size=20 )
arr2

array([60, 25, 94, 65, 24, 75, 59, 16, 89, 50, 55, 74, 62, 62, 16, 37, 53,
       99, 59, 52])

In [15]:
bigger = arr2[arr2>50]

In [16]:
bigger

array([60, 94, 65, 75, 59, 89, 55, 74, 62, 62, 53, 99, 59, 52])

In [17]:
arr3 = [60, 94, 65, 75, 59, 89, 55, 74, 62, 62]

In [18]:
np.random.shuffle(arr3)

In [19]:
arr3

[75, 62, 89, 59, 55, 60, 74, 65, 94, 62]

In [24]:
arr3[np.random.randint(1,10)]

60